name: Coverage
on: ["push", "pull_request"]
jobs:
  build:
    name: Check coverage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install deps and build
        run: npm i

      - name: Test
        run: npm run test

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3

